I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/options.rpy", line 58, in script
    define config.has_voice = false
  File "game/options.rpy", line 58, in <module>
    define config.has_voice = false
NameError: name 'false' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/options.rpy", line 58, in script
    define config.has_voice = false
  File "D:\Programs\renpy-6.99.12.1-sdk\renpy\ast.py", line 1946, in execute
    value = renpy.python.py_eval_bytecode(self.code.bytecode)
  File "D:\Programs\renpy-6.99.12.1-sdk\renpy\python.py", line 1912, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/options.rpy", line 58, in <module>
    define config.has_voice = false
NameError: name 'false' is not defined

Windows-8-6.2.9200
Ren'Py 6.99.14.3.3347
OBZH 1.0
Mon May 21 18:56:42 2018
